# Generated by Django 2.1.7 on 2019-03-07 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_newsfeed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircrafts',
            name='Name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='flights',
            name='Flight_No',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
